### ISSUE TITLE
Disk geometry auto calculation problem

### ISSUE THREAD

**Issue by acepow3r** [istvan-v/ep128emu#1] opened 2017-01-05 15:59 UTC
The bug occurs from version 2.0.10 stable till today:
Whenever the values of "Tracks", "Sides" and "Sectors per track", under Configure, are set to **-1**, for auto calculate, ep128emu returns an error saying "FDD: cannot determine size of disk image"
This is not the case with stable 2.0.9.1

**Comment by istvan-v** [comment] 2017-01-05 17:31
It works for me in 2.0.10 and 2.0.11 beta. Are you using an image file or a real floppy disk? If the latter, what operating system do you use? There have been some patches contributed by others to fix issues on recent versions of Windows, but I did not test these since I no longer have a PC with a floppy drive. If you used an image file, then was it formatted? The automatic configuration normally reads the disk geometry from the FAT file system header.

**Comment by acepow3r** [comment] 2017-01-05 19:24
Thanks for the reply!
I talk about disk images, 800k formatted and usable on 2.0.9.1. Your answer troubled me, so I did further tests:
I discovered that the problem is Windows oriented and occurring only when the disk image is at a folder or path with a **greek** localized name eg. C:\Users\Χρήστης\Documents\ROMs gives the error.
So D:\test\ROMs is OK but D:\τεστ\ROMs it isn't.
Any hope to fix that?

**Comment by istvan-v** [comment] 2017-01-05 21:59
Thanks for the information, I can reproduce the error now. It seems to be caused by fopen() not supporting UTF-8 on Windows, while newer versions of FLTK use UTF-8. It may not be easy to fully fix this, however, since all the file I/O would need to be changed, the issue is not specific to disk images.

**Comment by istvan-v** [comment] 2017-01-06 10:26
The problem is now fixed in the Git source code, although not for all types of file I/O: the installer, configuration file paths and utilities still do not support Unicode characters on Windows.

**Comment by istvan-v** [comment] 2017-01-08 10:00
There is a new beta build for Windows at the enterpriseforever.com forum [here](https://enterpriseforever.com/ep128emu/ep128emu/msg61441/#msg61441), it includes the UTF-8 fix.

**Closed as completed** 2017-01-10 20:00 UTC
